version: '3.8'

networks:
  bkhouse-network:
    driver: bridge

services:
  # 1. API Gateway (Định tuyến giao thông)
  nginx:
    image: nginx:alpine
    container_name: bkhouse-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bkhouse-network
    depends_on:
      - frontend
      - backend
      - socket
      - airflow

  # 2. Giao diện người dùng
  frontend:
    image: ducminh204/bkhouse-frontend:latest
    container_name: bkhouse-frontend
    expose: ["80"]
    networks:
      - bkhouse-network
    restart: unless-stopped

  # 3. Luồng xử lý nghiệp vụ chính (API)
  backend:
    image: ducminh204/bkhouse-backend1:latest
    container_name: bkhouse-backend
    expose: ["8080"]
    env_file: [.env]
    networks:
      - bkhouse-network
    restart: unless-stopped

  # 4. Máy chủ Realtime Chat (Socket)
  socket:
    image: ducminh204/bkhouse-backend2:latest
    container_name: bkhouse-socket
    expose: ["${SOCKET_PORT}"] # Lấy động từ file .env
    env_file: [.env]
    networks:
      - bkhouse-network
    restart: unless-stopped

  # 5. Hệ thống ETL & AI Pipeline
  airflow:
    image: ducminh204/bkhouse-airflow:latest
    container_name: bkhouse-airflow
    expose: ["8080"]
    env_file: [.env]
    networks:
      - bkhouse-network
    # Khởi tạo Airflow cơ bản
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true && airflow webserver & airflow scheduler"