services:
  frontend:
    image: ducminh204/bkhouse-frontend:latest
    restart: always
    expose: ["80"]

  backend:
    image: ducminh204/bkhouse-backend1:latest
    restart: always
    env_file: .env
    volumes:
      - ./fcm.json:/app/fcm.json:ro
    expose: ["7979"]

  socket:
    image: ducminh204/bkhouse-backend2:latest
    restart: always
    env_file: .env
    expose: ["3000"]

  nginx:
    image: nginx:1.27-alpine
    restart: always
    ports: ["80:80", "443:443"]
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on: [frontend, backend, socket]

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"
#dd