server {
    listen 80;
    server_name _; # Nhận mọi request khi chưa có domain

    # 1. Routing cho Angular (Frontend)
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 2. Routing cho Spring Boot API
    location /api/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Routing cho Airflow Webserver
    location /airflow/ {
        proxy_pass http://airflow:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 4. Routing riêng cho Socket (Cực kỳ quan trọng để không rớt kết nối Chat)
    location /socket.io/ {
        proxy_pass http://socket:9092; # Phải khớp với SOCKET_PORT
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}